itsstacy/tuttimusicFE

src/pages/SignUp.js, src/styles/App.css
=> 회원가입 페이지 완료!

src/App.js, src/pages/Upload.js, src/pages/UploadChoice.js, src/pages/UploadVideo.js
=> Upload 페이지 완성

src/App.js, src/components/Navbar.js, src/pages/FaceChat.js, src/pages/Live.js
뷰 그리고 이름도 바꿨습니다 
App 컴포넌트에도 변경했으니 확인 부탁드려요
=> Live 컴포넌트 뷰 구현 완료 

src/App.js, src/pages/DetailVideo.js, src/styles/App.css
Detailvideo 컴포넌트 생성해 비디오 얹어두었습니다. 
배치는 임의적으로 해두었습니다.
=> Detailvideo 컴포넌트 생성

.github/workflows/test.yml, src/elements/EditDelete.js, src/pages/Detail.js, src/pages/DetailVideo.js, src/pages/Edit.js, src/pages/Upload.js, src/pages/UploadChoice.js, src/pages/UploadVideo.js, src/styles/App.css
Upload / Detail 페이지 부분 작게작게 수정하고 고쳤습니다.
=> Upload / Detail 수정

src/pages/Edit.js, src/pages/MyEdit.js, src/pages/SignUp.js, src/pages/Upload.js, src/pages/UploadVideo.js
=> Signup / MyEdit / Upload / Edit 작업

src/elements/Waveform.js, src/pages/Detail.js, src/styles/App.css
- waveform 부분 디자인 검토 한번 더 한다음 하트랑 볼륨키랑 이동시킬게요.
지금 좀 어색한거같아서.. 이게 최종인지 물어봐야할거같아요
=> detail에 waveform 부분수정했습니다

src/App.js, src/pages/FaceChatList.js, src/pages/SignUp.js, src/styles/App.css
=> facechat list 뷰 + 회원가입 css 부분 정리

src/pages/MyPage.js, src/pages/UserPage.js, src/styles/App.css
마이페이지 수정 버튼 + 타인 페이지 팔로우 버튼 + sns
=> 마이페이지 수정 버튼 + 타인 페이지 팔로우 버튼

src/components/Navbar.js, src/elements/Tab1.js, src/elements/Tab2.js, src/elements/Tab3.js, src/elements/Tab4.js, src/elements/Tab5.js, src/elements/Tab6.js, src/pages/Detail.js, src/pages/MyEdit.js, src/pages/UserPage.js, src/styles/App.css
=> 마이페이지 tab 작업

src/pages/MyPage.js, src/pages/UserPage.js, src/styles/App.css
마이페이지 + 타인페이지 sns 아이콘 눌렀을 때,
해당 주소로 이동하는 부분
=> Sns button

package.json, src/pages/FaceChatList.js, src/styles/App.css
화상채팅 페이지 버튼 추가 및 css 작업 했습니다...
=> 화상채팅 페이지 버튼 추가

src/pages/Main.js, src/styles/App.css
메인 페이지에 장르 부분 => 어떤 장르인지 보여주는 것 완성
=> 메인 페이지 장르 부분 옆 장르 표시

src/styles/App.css
화상채팅 리스트 페이지에서 버튼에 마우스 올렸을 때, pointer로 나오는 부분
=> 라이브 시작하기 포인터

src/elements/Streamer.js, src/pages/Main.js, src/styles/App.css
라이브에 카메라/마이크 엑세스 요청하기 추가 및 css 수정
=> 라이브에 카메라/마이크 엑세스 요청하기 추가 및 css 수정

src/App.js, src/components/Navbar.js, src/pages/CreateLive.js, src/pages/Detail.js, src/pages/DetailVideo.js, src/pages/FaceChatList.js, src/pages/Login.js, src/pages/NotFound.js, src/pages/SignUp.js, src/pages/Upload.js, src/pages/UploadVideo.js, src/pages/UserPage.js, src/styles/App.css
=> 비정상적인 접근 막는 작업

src/components/Player.js, src/elements/Chatbox.js, src/elements/Streamer.js, src/pages/FaceChatList.js, src/pages/Live.js, src/pages/MusicFeed.js, src/pages/UploadChoice.js, src/styles/App.css
라이브 기능, 무한 스크롤 문제 해결
삭제하면 방이 없어지는 부분 아직 백엔드에서 작업중입니다.
=> 라이브 기능, 무한 스크롤 문제 해결

src/pages/Detail.js, src/pages/DetailVideo.js, src/pages/MusicFeed.js, src/pages/SignUp.js, src/styles/App.css
=> 곡 / 영상 소개글 부분 

src/pages/SignUp.js, src/styles/App.css
=> Email check

src/App.js, src/pages/EmailCheck.js, src/pages/SearchResult.js, src/styles/App.css
이메일 인증 페이지 일단 만들었습니다....
정윤님의 의견을 들어야하지만....
=> 이메일 인증 페이지

src/App.js, src/pages/SearchResult.js, src/redux/modules/songSlice.js, src/styles/App.css
=> 검색 더보기 기능 완료

src/components/Navbar.js, src/components/Player.js, src/elements/Blocker.js, src/elements/Chatbox.js, src/elements/Intro.js, src/elements/Streamer.js, src/elements/Waveform.js, src/pages/Live.js, src/styles/App.css
=> Modal and debug

package-lock.json, package.json, src/App.js, src/components/Footer.js, src/components/Player.js, src/elements/Waveform.js, src/pages/Detail.js, src/pages/Main.js, src/pages/SignUp.js, src/pages/Upload.js, src/pages/UploadVideo.js, src/redux/modules/playerSlice.js, src/styles/App.css, yarn.lock
=> Player, agreeterms (signup)

src/App.js, src/pages/MyEdit.js, src/styles/Mq_smscreen.css
=> Screen1920

public/index.html, src/pages/MyEdit.js, src/pages/SignUp.js, src/pages/UserPage.js, src/redux/modules/songSlice.js, src/redux/modules/userSlice.js
=> goChange2, debug

src/pages/Detail.js, src/pages/DetailVideo.js, src/styles/App.css, src/styles/Mq_smscreen.css
=> 디테일 페이지 장르 추가

src/components/Player.js, src/elements/Chatbox.js, src/elements/Waveform.js, src/redux/modules/playerSlice.js
2. 음악 재생 끝났을 때 음악이 멈추고 플레이 버튼으로 바뀌는데, 이때 플레이 누르면 다시 처음부터 플레이 됨
=> 1. 음악 재생이 끝나면 play/pause 버튼 뒤바뀌는 현상 해소

src/pages/MyEdit.js, src/pages/SignUp.js, src/pages/UserPage.js, src/styles/App.css, src/styles/Mq_mobile.css, src/styles/Mq_smscreen.css
팔로잉 시, 버튼 css 변경 
장르 선택 시, 버튼 css 변경 ( 회원가입 / 회원 정보 수정 페이지 )
=> Button css

src/components/Player.js
2. 플레이어의 소리조절을 누르고 X를 누르면 → 흰색화면 발생 -> 수정
=> 1. 플레이어 X를 누르고 소리조절 → 흰색화면 발생-> 수정

src/styles/Mq_mobile.css
live video control
padding & margins
remove scrolltop button
=> 모바일 버전 css 수정:
